# Generated by Django 5.1.2 on 2024-11-03 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_tableresto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableresto',
            old_name='table_choices',
            new_name='table_status',
        ),
    ]
